stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/car_prices.csv
    outs:
      - data/raw/car_prices.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/car_prices.csv
    outs:
      - data/processed/train_car_prices.csv
      - data/processed/test_car_prices.csv
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py
    deps:
      - src/train_and_evaluate.py
      - data/processed/train_car_prices.csv
      - data/processed/test_car_prices.csv
    params:
      - Estimators.ElasticNet.params.alpha
      - Estimators.ElasticNet.params.l1_ratio
    metrics:
      - reports/params.json:
          cache: false
      - reports/scores.json:
          cache: false
    outs: 
      - saved_models/model.joblib